import sys
print(sys.version)
import PSG
from pathlib import Path

model_dir = Path("../ModelFiles")
gcm_files = model_dir.glob("trappist1e*1barN2*1barCO2*.avg.nc")

for i, fil in enumerate(gcm_files):
    print("File {}: {}".format(i + 1, fil))
    x = PSG.PSG("TRAPPIST-1 e")
    x.fetch_archive()
    x.from_cdf(fil, phase=180, is_transit=True)
    x.calculate(1e-6, 7)
    x.write("MIRI-MRS", rad_units="Wsrm2um")
    x.send(run=True)
    x.plot_setup()
    # x.depth_plot()
    # x.depth_height()
    # x.emission()
    # x.raw()
    # x.star()
    # x.signal_and_noise()
    # x.signal_noise_ratio()
    # x.absorption()
    # print("    Radiance Plots Complete")
    # x.trn_total()
    # x.trn_co2()
    # x.trn_n2()
    # x.trn_h2o()
    # x.trn_ice()
    # x.trn_cloud()
    # x.trn_cia()
    # x.trn_species()
    # x.trn_aerosols()
    # x.trn_all()
    # x.noise_components()
    # x.noise_ppm()
    # x.depth_noise()
print("PSG: Operation complete")
